### ISSUE TITLE
[Feature request] Add dataType field to sample2 API endpoint 

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-server#24]
It's possible to query for datatype (only surveillance or all), that's cool, but it'd be easier for users if the datatype was included in the returned data directly here https://github.com/cevo-public/cov-spectrum-docs/blob/develop/API.md#sample-new
```
[
  {
    date?: Date,
    region?: string,
    country?: string,
    division?: string,
    zipCode?: string,
    ageGroup?: string,
    sex?: "Male"|"Female",
    hospitalized?: boolean,
    deceased?: boolean,
    pangolinLineage?: string,
    dataType?: string,
    count: integer
  }
]
```

What information about dataType do you have for Switzerland? Is it just a boolean for surveillance or potentially more fine-grained, such as outbreak investigation etc.? That may be interesting for private endpoints.

**Comment by chaoran-chen** [comment]
Hi @corneliusroemer, thank you very much for the suggestion!

Currently, the only available dataType is SURVEILLANCE which is, right now, defined as sequences submitted by the S3C and HUG. There are certainly many other labs right now which also do surveillance but we haven't had the chance to talk to them and to understand their exact sampling procedure yet. GISAID also provides a field with information on the sampling background but we are not using it yet because we are not sure which labs are using it, how they use it, and whether they also updated the older data.

Adding the `dataType` field is a little difficult because we don't assign a fixed data type to each sample. Instead, the idea of this field is to enable us to define subsets of the data in a flexible way. For example, we could imagine adding more data. types such as Gisaid-only, non-human, or very-high-quality. These subsets would not be distinct so that `dataType?: string` certainly would not work but we would need to write `data: Array<string>`. This is, however, currently not easy to implement.

I will keep this issue open but I'm afraid that we won't be able to resolve it very soon.

**Comment by corneliusroemer** [comment]
Understood! Thanks for explaining in such detail. In that case I will happily add my own label by querying 😊

**Comment by chaoran-chen** [comment]
In [LAPIS](https://github.com/cevo-public/LAPIS), it is now possible to get the sampling strategy.
